spring:
log4j:
  logger:
    httpclient:
      wire: DEBUG

client:
  id: Tg0h1x1kHRI3KN0j0gG1jMC6IAWyRKAAWxAFfSQ-GBE=
  secret: IBO_t5J5piA-Q8twGQXmsABAGbNQaebtGf3AGtiRGGI=
  redirectUri: http://localhost:4001/redirecting/
  financialId: 0015800000jfwB4AAI
  state: ABC
  authorizationUsername: 123456789012@team.acc.org
  authorizationAccount: 50000012345601
  tokenUrl: https://ob.natwest.useinfinite.io/token
  initRunning: true


tls:
  alias:
  enableMatls: false
  keyStore:
    location:
    password:
  trustStore:
    location:
    password:

aisp:
  target:
    context: /open-banking/v3.1/aisp
    baseUri: https://ob.natwest.useinfinite.io
    audience: https://api.natwest.useinfinite.io/authorize

pisp:
  target:
    context: /open-banking/v3.1/pisp
    baseUri: https://ob.natwest.useinfinite.io
    audience: https://api.natwest.useinfinite.io/authorize